vich_uploader:
    db_driver: orm

    mappings:
        organisationLogo:
            uri_prefix: /images/organisations/logos
            upload_destination: '%kernel.project_dir%/public/images/organisations/logos'
            namer:
                service: Vich\UploaderBundle\Naming\HashNamer
