controllers:
    resource: ../src/Controller/SecurityController.php
    type: attribute

controllers_back:
    resource: ../src/Controller/Back
    type: attribute
    prefix: /admin
    name_prefix: back_

controllers_front:
    resource: ../src/Controller/Front
    type: attribute
    name_prefix: front_
